require 'spec_helper'

describe "score_cards/new.html.erb" do
  before(:each) do
    assign(:score_card, stub_model(ScoreCard,
      :user_id => 1,
      :course_id => 1,
      :tee_box => "MyString",
      :course2_id => 1,
      :start_hole => 1,
      :score => 1,
      :hole1_id => 1,
      :score1 => 1,
      :putts1 => 1,
      :t_club1 => "MyString",
      :fairway1 => "MyString",
      :sand1 => 1,
      :pty1 => 1,
      :hole2_id => 1,
      :score2 => 1,
      :putts2 => 1,
      :t_club2 => "MyString",
      :fairway2 => "MyString",
      :sand2 => 1,
      :pty2 => 1,
      :hole3_id => 1,
      :score3 => 1,
      :putts3 => 1,
      :t_club3 => "MyString",
      :fairway3 => "MyString",
      :sand3 => 1,
      :pty3 => 1,
      :hole4_id => 1,
      :score4 => 1,
      :putts4 => 1,
      :t_club4 => "MyString",
      :fairway4 => "MyString",
      :sand4 => 1,
      :pty4 => 1,
      :hole5_id => 1,
      :score5 => 1,
      :putts5 => 1,
      :t_club5 => "MyString",
      :fairway5 => "MyString",
      :sand5 => 1,
      :pty5 => 1,
      :hole6_id => 1,
      :score6 => 1,
      :putts6 => 1,
      :t_club6 => "MyString",
      :fairway6 => "MyString",
      :sand6 => 1,
      :pty6 => 1,
      :hole7_id => 1,
      :score7 => 1,
      :putts7 => 1,
      :t_club7 => "MyString",
      :fairway7 => "MyString",
      :sand7 => 1,
      :pty7 => 1,
      :hole8_id => 1,
      :score8 => 1,
      :putts8 => 1,
      :t_club8 => "MyString",
      :fairway8 => "MyString",
      :sand8 => 1,
      :pty8 => 1,
      :hole9_id => 1,
      :score9 => 1,
      :putts9 => 1,
      :t_club9 => "MyString",
      :fairway9 => "MyString",
      :sand9 => 1,
      :pty9 => 1,
      :hole10_id => 1,
      :score10 => 1,
      :putts10 => 1,
      :t_club10 => "MyString",
      :fairway10 => "MyString",
      :sand10 => 1,
      :pty10 => 1,
      :hole11_id => 1,
      :score11 => 1,
      :putts11 => 1,
      :t_club11 => "MyString",
      :fairway11 => "MyString",
      :sand11 => 1,
      :pty11 => 1,
      :hole12_id => 1,
      :score12 => 1,
      :putts12 => 1,
      :t_club12 => "MyString",
      :fairway12 => "MyString",
      :sand12 => 1,
      :pty12 => 1,
      :hole13_id => 1,
      :score13 => 1,
      :putts13 => 1,
      :t_club13 => "MyString",
      :fairway13 => "MyString",
      :sand13 => 1,
      :pty13 => 1,
      :hole14_id => 1,
      :score14 => 1,
      :putts14 => 1,
      :t_club14 => "MyString",
      :fairway14 => "MyString",
      :sand14 => 1,
      :pty14 => 1,
      :hole15_id => 1,
      :score15 => 1,
      :putts15 => 1,
      :t_club15 => "MyString",
      :fairway15 => "MyString",
      :sand15 => 1,
      :pty15 => 1,
      :hole16_id => 1,
      :score16 => 1,
      :putts16 => 1,
      :t_club16 => "MyString",
      :fairway16 => "MyString",
      :sand16 => 1,
      :pty16 => 1,
      :hole17_id => 1,
      :score17 => 1,
      :putts17 => 1,
      :t_club17 => "MyString",
      :fairway17 => "MyString",
      :sand17 => 1,
      :pty17 => 1,
      :hole18_id => 1,
      :score18 => 1,
      :putts18 => 1,
      :t_club18 => "MyString",
      :fairway18 => "MyString",
      :sand18 => 1,
      :pty18 => 1
    ).as_new_record)
  end

  it "renders new score_card form" do
    render

    # Run the generator again with the --webrat flag if you want to use webrat matchers
    assert_select "form", :action => score_cards_path, :method => "post" do
      assert_select "input#score_card_user_id", :name => "score_card[user_id]"
      assert_select "input#score_card_course_id", :name => "score_card[course_id]"
      assert_select "input#score_card_tee_box", :name => "score_card[tee_box]"
      assert_select "input#score_card_course2_id", :name => "score_card[course2_id]"
      assert_select "input#score_card_start_hole", :name => "score_card[start_hole]"
      assert_select "input#score_card_score", :name => "score_card[score]"
      assert_select "input#score_card_hole1_id", :name => "score_card[hole1_id]"
      assert_select "input#score_card_score1", :name => "score_card[score1]"
      assert_select "input#score_card_putts1", :name => "score_card[putts1]"
      assert_select "input#score_card_t_club1", :name => "score_card[t_club1]"
      assert_select "input#score_card_fairway1", :name => "score_card[fairway1]"
      assert_select "input#score_card_sand1", :name => "score_card[sand1]"
      assert_select "input#score_card_pty1", :name => "score_card[pty1]"
      assert_select "input#score_card_hole2_id", :name => "score_card[hole2_id]"
      assert_select "input#score_card_score2", :name => "score_card[score2]"
      assert_select "input#score_card_putts2", :name => "score_card[putts2]"
      assert_select "input#score_card_t_club2", :name => "score_card[t_club2]"
      assert_select "input#score_card_fairway2", :name => "score_card[fairway2]"
      assert_select "input#score_card_sand2", :name => "score_card[sand2]"
      assert_select "input#score_card_pty2", :name => "score_card[pty2]"
      assert_select "input#score_card_hole3_id", :name => "score_card[hole3_id]"
      assert_select "input#score_card_score3", :name => "score_card[score3]"
      assert_select "input#score_card_putts3", :name => "score_card[putts3]"
      assert_select "input#score_card_t_club3", :name => "score_card[t_club3]"
      assert_select "input#score_card_fairway3", :name => "score_card[fairway3]"
      assert_select "input#score_card_sand3", :name => "score_card[sand3]"
      assert_select "input#score_card_pty3", :name => "score_card[pty3]"
      assert_select "input#score_card_hole4_id", :name => "score_card[hole4_id]"
      assert_select "input#score_card_score4", :name => "score_card[score4]"
      assert_select "input#score_card_putts4", :name => "score_card[putts4]"
      assert_select "input#score_card_t_club4", :name => "score_card[t_club4]"
      assert_select "input#score_card_fairway4", :name => "score_card[fairway4]"
      assert_select "input#score_card_sand4", :name => "score_card[sand4]"
      assert_select "input#score_card_pty4", :name => "score_card[pty4]"
      assert_select "input#score_card_hole5_id", :name => "score_card[hole5_id]"
      assert_select "input#score_card_score5", :name => "score_card[score5]"
      assert_select "input#score_card_putts5", :name => "score_card[putts5]"
      assert_select "input#score_card_t_club5", :name => "score_card[t_club5]"
      assert_select "input#score_card_fairway5", :name => "score_card[fairway5]"
      assert_select "input#score_card_sand5", :name => "score_card[sand5]"
      assert_select "input#score_card_pty5", :name => "score_card[pty5]"
      assert_select "input#score_card_hole6_id", :name => "score_card[hole6_id]"
      assert_select "input#score_card_score6", :name => "score_card[score6]"
      assert_select "input#score_card_putts6", :name => "score_card[putts6]"
      assert_select "input#score_card_t_club6", :name => "score_card[t_club6]"
      assert_select "input#score_card_fairway6", :name => "score_card[fairway6]"
      assert_select "input#score_card_sand6", :name => "score_card[sand6]"
      assert_select "input#score_card_pty6", :name => "score_card[pty6]"
      assert_select "input#score_card_hole7_id", :name => "score_card[hole7_id]"
      assert_select "input#score_card_score7", :name => "score_card[score7]"
      assert_select "input#score_card_putts7", :name => "score_card[putts7]"
      assert_select "input#score_card_t_club7", :name => "score_card[t_club7]"
      assert_select "input#score_card_fairway7", :name => "score_card[fairway7]"
      assert_select "input#score_card_sand7", :name => "score_card[sand7]"
      assert_select "input#score_card_pty7", :name => "score_card[pty7]"
      assert_select "input#score_card_hole8_id", :name => "score_card[hole8_id]"
      assert_select "input#score_card_score8", :name => "score_card[score8]"
      assert_select "input#score_card_putts8", :name => "score_card[putts8]"
      assert_select "input#score_card_t_club8", :name => "score_card[t_club8]"
      assert_select "input#score_card_fairway8", :name => "score_card[fairway8]"
      assert_select "input#score_card_sand8", :name => "score_card[sand8]"
      assert_select "input#score_card_pty8", :name => "score_card[pty8]"
      assert_select "input#score_card_hole9_id", :name => "score_card[hole9_id]"
      assert_select "input#score_card_score9", :name => "score_card[score9]"
      assert_select "input#score_card_putts9", :name => "score_card[putts9]"
      assert_select "input#score_card_t_club9", :name => "score_card[t_club9]"
      assert_select "input#score_card_fairway9", :name => "score_card[fairway9]"
      assert_select "input#score_card_sand9", :name => "score_card[sand9]"
      assert_select "input#score_card_pty9", :name => "score_card[pty9]"
      assert_select "input#score_card_hole10_id", :name => "score_card[hole10_id]"
      assert_select "input#score_card_score10", :name => "score_card[score10]"
      assert_select "input#score_card_putts10", :name => "score_card[putts10]"
      assert_select "input#score_card_t_club10", :name => "score_card[t_club10]"
      assert_select "input#score_card_fairway10", :name => "score_card[fairway10]"
      assert_select "input#score_card_sand10", :name => "score_card[sand10]"
      assert_select "input#score_card_pty10", :name => "score_card[pty10]"
      assert_select "input#score_card_hole11_id", :name => "score_card[hole11_id]"
      assert_select "input#score_card_score11", :name => "score_card[score11]"
      assert_select "input#score_card_putts11", :name => "score_card[putts11]"
      assert_select "input#score_card_t_club11", :name => "score_card[t_club11]"
      assert_select "input#score_card_fairway11", :name => "score_card[fairway11]"
      assert_select "input#score_card_sand11", :name => "score_card[sand11]"
      assert_select "input#score_card_pty11", :name => "score_card[pty11]"
      assert_select "input#score_card_hole12_id", :name => "score_card[hole12_id]"
      assert_select "input#score_card_score12", :name => "score_card[score12]"
      assert_select "input#score_card_putts12", :name => "score_card[putts12]"
      assert_select "input#score_card_t_club12", :name => "score_card[t_club12]"
      assert_select "input#score_card_fairway12", :name => "score_card[fairway12]"
      assert_select "input#score_card_sand12", :name => "score_card[sand12]"
      assert_select "input#score_card_pty12", :name => "score_card[pty12]"
      assert_select "input#score_card_hole13_id", :name => "score_card[hole13_id]"
      assert_select "input#score_card_score13", :name => "score_card[score13]"
      assert_select "input#score_card_putts13", :name => "score_card[putts13]"
      assert_select "input#score_card_t_club13", :name => "score_card[t_club13]"
      assert_select "input#score_card_fairway13", :name => "score_card[fairway13]"
      assert_select "input#score_card_sand13", :name => "score_card[sand13]"
      assert_select "input#score_card_pty13", :name => "score_card[pty13]"
      assert_select "input#score_card_hole14_id", :name => "score_card[hole14_id]"
      assert_select "input#score_card_score14", :name => "score_card[score14]"
      assert_select "input#score_card_putts14", :name => "score_card[putts14]"
      assert_select "input#score_card_t_club14", :name => "score_card[t_club14]"
      assert_select "input#score_card_fairway14", :name => "score_card[fairway14]"
      assert_select "input#score_card_sand14", :name => "score_card[sand14]"
      assert_select "input#score_card_pty14", :name => "score_card[pty14]"
      assert_select "input#score_card_hole15_id", :name => "score_card[hole15_id]"
      assert_select "input#score_card_score15", :name => "score_card[score15]"
      assert_select "input#score_card_putts15", :name => "score_card[putts15]"
      assert_select "input#score_card_t_club15", :name => "score_card[t_club15]"
      assert_select "input#score_card_fairway15", :name => "score_card[fairway15]"
      assert_select "input#score_card_sand15", :name => "score_card[sand15]"
      assert_select "input#score_card_pty15", :name => "score_card[pty15]"
      assert_select "input#score_card_hole16_id", :name => "score_card[hole16_id]"
      assert_select "input#score_card_score16", :name => "score_card[score16]"
      assert_select "input#score_card_putts16", :name => "score_card[putts16]"
      assert_select "input#score_card_t_club16", :name => "score_card[t_club16]"
      assert_select "input#score_card_fairway16", :name => "score_card[fairway16]"
      assert_select "input#score_card_sand16", :name => "score_card[sand16]"
      assert_select "input#score_card_pty16", :name => "score_card[pty16]"
      assert_select "input#score_card_hole17_id", :name => "score_card[hole17_id]"
      assert_select "input#score_card_score17", :name => "score_card[score17]"
      assert_select "input#score_card_putts17", :name => "score_card[putts17]"
      assert_select "input#score_card_t_club17", :name => "score_card[t_club17]"
      assert_select "input#score_card_fairway17", :name => "score_card[fairway17]"
      assert_select "input#score_card_sand17", :name => "score_card[sand17]"
      assert_select "input#score_card_pty17", :name => "score_card[pty17]"
      assert_select "input#score_card_hole18_id", :name => "score_card[hole18_id]"
      assert_select "input#score_card_score18", :name => "score_card[score18]"
      assert_select "input#score_card_putts18", :name => "score_card[putts18]"
      assert_select "input#score_card_t_club18", :name => "score_card[t_club18]"
      assert_select "input#score_card_fairway18", :name => "score_card[fairway18]"
      assert_select "input#score_card_sand18", :name => "score_card[sand18]"
      assert_select "input#score_card_pty18", :name => "score_card[pty18]"
    end
  end
end
