class CreateScoreCards < ActiveRecord::Migration
  def change
    create_table :score_cards do |t|
      t.integer :user_id
      t.integer :course_id
      t.string :tee_box
      t.integer :course2_id
      t.integer :start_hole
      t.integer :score
      t.integer :hole1_id
      t.integer :score1
      t.integer :putts1
      t.string :t_club1
      t.string :fairway1
      t.integer :sand1
      t.integer :pty1
      t.integer :hole2_id
      t.integer :score2
      t.integer :putts2
      t.string :t_club2
      t.string :fairway2
      t.integer :sand2
      t.integer :pty2
      t.integer :hole3_id
      t.integer :score3
      t.integer :putts3
      t.string :t_club3
      t.string :fairway3
      t.integer :sand3
      t.integer :pty3
      t.integer :hole4_id
      t.integer :score4
      t.integer :putts4
      t.string :t_club4
      t.string :fairway4
      t.integer :sand4
      t.integer :pty4
      t.integer :hole5_id
      t.integer :score5
      t.integer :putts5
      t.string :t_club5
      t.string :fairway5
      t.integer :sand5
      t.integer :pty5
      t.integer :hole6_id
      t.integer :score6
      t.integer :putts6
      t.string :t_club6
      t.string :fairway6
      t.integer :sand6
      t.integer :pty6
      t.integer :hole7_id
      t.integer :score7
      t.integer :putts7
      t.string :t_club7
      t.string :fairway7
      t.integer :sand7
      t.integer :pty7
      t.integer :hole8_id
      t.integer :score8
      t.integer :putts8
      t.string :t_club8
      t.string :fairway8
      t.integer :sand8
      t.integer :pty8
      t.integer :hole9_id
      t.integer :score9
      t.integer :putts9
      t.string :t_club9
      t.string :fairway9
      t.integer :sand9
      t.integer :pty9
      t.integer :hole10_id
      t.integer :score10
      t.integer :putts10
      t.string :t_club10
      t.string :fairway10
      t.integer :sand10
      t.integer :pty10
      t.integer :hole11_id
      t.integer :score11
      t.integer :putts11
      t.string :t_club11
      t.string :fairway11
      t.integer :sand11
      t.integer :pty11
      t.integer :hole12_id
      t.integer :score12
      t.integer :putts12
      t.string :t_club12
      t.string :fairway12
      t.integer :sand12
      t.integer :pty12
      t.integer :hole13_id
      t.integer :score13
      t.integer :putts13
      t.string :t_club13
      t.string :fairway13
      t.integer :sand13
      t.integer :pty13
      t.integer :hole14_id
      t.integer :score14
      t.integer :putts14
      t.string :t_club14
      t.string :fairway14
      t.integer :sand14
      t.integer :pty14
      t.integer :hole15_id
      t.integer :score15
      t.integer :putts15
      t.string :t_club15
      t.string :fairway15
      t.integer :sand15
      t.integer :pty15
      t.integer :hole16_id
      t.integer :score16
      t.integer :putts16
      t.string :t_club16
      t.string :fairway16
      t.integer :sand16
      t.integer :pty16
      t.integer :hole17_id
      t.integer :score17
      t.integer :putts17
      t.string :t_club17
      t.string :fairway17
      t.integer :sand17
      t.integer :pty17
      t.integer :hole18_id
      t.integer :score18
      t.integer :putts18
      t.string :t_club18
      t.string :fairway18
      t.integer :sand18
      t.integer :pty18

      t.timestamps
    end
  end
end
