require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HolesController do

  # This should return the minimal set of attributes required to create a valid
  # Hole. As you add validations to Hole, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all holes as @holes" do
      hole = Hole.create! valid_attributes
      get :index
      assigns(:holes).should eq([hole])
    end
  end

  describe "GET show" do
    it "assigns the requested hole as @hole" do
      hole = Hole.create! valid_attributes
      get :show, :id => hole.id.to_s
      assigns(:hole).should eq(hole)
    end
  end

  describe "GET new" do
    it "assigns a new hole as @hole" do
      get :new
      assigns(:hole).should be_a_new(Hole)
    end
  end

  describe "GET edit" do
    it "assigns the requested hole as @hole" do
      hole = Hole.create! valid_attributes
      get :edit, :id => hole.id.to_s
      assigns(:hole).should eq(hole)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hole" do
        expect {
          post :create, :hole => valid_attributes
        }.to change(Hole, :count).by(1)
      end

      it "assigns a newly created hole as @hole" do
        post :create, :hole => valid_attributes
        assigns(:hole).should be_a(Hole)
        assigns(:hole).should be_persisted
      end

      it "redirects to the created hole" do
        post :create, :hole => valid_attributes
        response.should redirect_to(Hole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hole as @hole" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hole.any_instance.stub(:save).and_return(false)
        post :create, :hole => {}
        assigns(:hole).should be_a_new(Hole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hole.any_instance.stub(:save).and_return(false)
        post :create, :hole => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hole" do
        hole = Hole.create! valid_attributes
        # Assuming there are no other holes in the database, this
        # specifies that the Hole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hole.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hole.id, :hole => {'these' => 'params'}
      end

      it "assigns the requested hole as @hole" do
        hole = Hole.create! valid_attributes
        put :update, :id => hole.id, :hole => valid_attributes
        assigns(:hole).should eq(hole)
      end

      it "redirects to the hole" do
        hole = Hole.create! valid_attributes
        put :update, :id => hole.id, :hole => valid_attributes
        response.should redirect_to(hole)
      end
    end

    describe "with invalid params" do
      it "assigns the hole as @hole" do
        hole = Hole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hole.any_instance.stub(:save).and_return(false)
        put :update, :id => hole.id.to_s, :hole => {}
        assigns(:hole).should eq(hole)
      end

      it "re-renders the 'edit' template" do
        hole = Hole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hole.any_instance.stub(:save).and_return(false)
        put :update, :id => hole.id.to_s, :hole => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hole" do
      hole = Hole.create! valid_attributes
      expect {
        delete :destroy, :id => hole.id.to_s
      }.to change(Hole, :count).by(-1)
    end

    it "redirects to the holes list" do
      hole = Hole.create! valid_attributes
      delete :destroy, :id => hole.id.to_s
      response.should redirect_to(holes_url)
    end
  end

end
