require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScoreCardsController do

  # This should return the minimal set of attributes required to create a valid
  # ScoreCard. As you add validations to ScoreCard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all score_cards as @score_cards" do
      score_card = ScoreCard.create! valid_attributes
      get :index
      assigns(:score_cards).should eq([score_card])
    end
  end

  describe "GET show" do
    it "assigns the requested score_card as @score_card" do
      score_card = ScoreCard.create! valid_attributes
      get :show, :id => score_card.id.to_s
      assigns(:score_card).should eq(score_card)
    end
  end

  describe "GET new" do
    it "assigns a new score_card as @score_card" do
      get :new
      assigns(:score_card).should be_a_new(ScoreCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested score_card as @score_card" do
      score_card = ScoreCard.create! valid_attributes
      get :edit, :id => score_card.id.to_s
      assigns(:score_card).should eq(score_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScoreCard" do
        expect {
          post :create, :score_card => valid_attributes
        }.to change(ScoreCard, :count).by(1)
      end

      it "assigns a newly created score_card as @score_card" do
        post :create, :score_card => valid_attributes
        assigns(:score_card).should be_a(ScoreCard)
        assigns(:score_card).should be_persisted
      end

      it "redirects to the created score_card" do
        post :create, :score_card => valid_attributes
        response.should redirect_to(ScoreCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved score_card as @score_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreCard.any_instance.stub(:save).and_return(false)
        post :create, :score_card => {}
        assigns(:score_card).should be_a_new(ScoreCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreCard.any_instance.stub(:save).and_return(false)
        post :create, :score_card => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested score_card" do
        score_card = ScoreCard.create! valid_attributes
        # Assuming there are no other score_cards in the database, this
        # specifies that the ScoreCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScoreCard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => score_card.id, :score_card => {'these' => 'params'}
      end

      it "assigns the requested score_card as @score_card" do
        score_card = ScoreCard.create! valid_attributes
        put :update, :id => score_card.id, :score_card => valid_attributes
        assigns(:score_card).should eq(score_card)
      end

      it "redirects to the score_card" do
        score_card = ScoreCard.create! valid_attributes
        put :update, :id => score_card.id, :score_card => valid_attributes
        response.should redirect_to(score_card)
      end
    end

    describe "with invalid params" do
      it "assigns the score_card as @score_card" do
        score_card = ScoreCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreCard.any_instance.stub(:save).and_return(false)
        put :update, :id => score_card.id.to_s, :score_card => {}
        assigns(:score_card).should eq(score_card)
      end

      it "re-renders the 'edit' template" do
        score_card = ScoreCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreCard.any_instance.stub(:save).and_return(false)
        put :update, :id => score_card.id.to_s, :score_card => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested score_card" do
      score_card = ScoreCard.create! valid_attributes
      expect {
        delete :destroy, :id => score_card.id.to_s
      }.to change(ScoreCard, :count).by(-1)
    end

    it "redirects to the score_cards list" do
      score_card = ScoreCard.create! valid_attributes
      delete :destroy, :id => score_card.id.to_s
      response.should redirect_to(score_cards_url)
    end
  end

end
